@c_sharp_api_HostAddress = http://localhost:5113

GET {{c_sharp_api_HostAddress}}/weatherforecast/
Accept: application/json

GET {{c_sharp_api_HostAddress}}/besttimetobyorsellstock/
Accept: application/json

GET {{c_sharp_api_HostAddress}}/longestpalidromicsubstring/
Accept: application/json

###
