@c_sharp_api_HostAddress = http://localhost:5113

GET {{c_sharp_api_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{c_sharp_api_HostAddress}}/besttimetobyorsellstock/
Accept: application/json
Content-Type: application/json

{
	"prices": [7, 1, 5, 3, 6, 4]
}

###

POST {{c_sharp_api_HostAddress}}/longestpalidromicsubstring/
Accept: application/json
Content-Type: application/json

{
	"s": "babad"
}

###
